### ISSUE TITLE
multilevel.cor( ): Error in UseMethod(lavInspect)

### ISSUE THREAD

**Issue by RichardJanzen** [cran/misty#1]
Dear Dr. Yanagida,

when using the multilevel.cor-Function, I stumbled upon the following error:
```
Error in UseMethod("lavInspect", object) : 
  no applicable method for 'lavInspect' applied to an object of class "NULL"
```
Which stopped the printing of the results and as such also prohibits that the object is returned.

When further investigating it, I found that the error probably came from the print.misty.object.R. More specifically from line 4691
https://github.com/cran/misty/blob/1e963bcae8fabbd3f6bcdb8e15ffe2d3e6931284/R/print.misty.object.R#L4691

It expects the object passed to it to have the element `mod.fit`. However, inside the multilevel.cor function, it is being defined as `model.fit`.
https://github.com/cran/misty/blob/1e963bcae8fabbd3f6bcdb8e15ffe2d3e6931284/R/multilevel.cor.R#LL736C25-L736C25
```
object <- list(call = match.call(),
                 type = "multilevel.cor",
                 data = x,
                 args = list(within = within, between = between,
                             estimator = estimator, missing = missing,
                             sig = sig, alpha = alpha, print = print,
                             split = split, tri = tri, tri.lower = tri.lower,
                             p.adj = p.adj, digits = digits, p.digits = p.digits,
                             as.na = as.na, check = check, output = output),
                 model.fit = mod.fit,
                 result = list(summary = lavaan.summary,
                               wb.cor = wb.cor, wb.se = wb.se,
                               wb.stat = wb.stat, wb.p = wb.p,
                               with.cor = with.cor, with.se = with.se,
                               with.stat = with.stat, with.p = with.p,
                               betw.cor = betw.cor, betw.se = betw.se,
                               betw.stat = betw.stat, betw.p = betw.p))
```

Is this in fact an error? Or is it something on my side?
Interestingly, the error was not thrown in my colleagues project.

Best Regards
Richard Janzen

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
